{% set version = '1.9-61' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pcapp
  version: {{ version|replace("-", "_") }}

source:
  fn: pcaPP_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pcaPP_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pcaPP/pcaPP_{{ version }}.tar.gz
  sha256: 7dc395e159ff1a56135baaf0b1bea40f871c30f6dadd38992f4ccdfc4e88dc29

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-mvtnorm

  run:
    - r-base
    - r-mvtnorm

test:
  commands:
    - $R -e "library('pcaPP')"  # [not win]
    - "\"%R%\" -e \"library('pcaPP')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pcaPP
  license: GPL (>= 3)
  summary: Provides functions for robust PCA by projection pursuit.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
