appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: NXnFQ0uijaDKPOV9xoEwummfGWiCzZFpn+9BuCBsQeVen98ZeiibJS0um6UawFCNXuOg3XObdW6J02pRl+/gb2BhDwoVjMDSgi6eG8wd9iD9AGQbZmG6tuNdHBMI4q119vA7eZ5LFwpUhJAbNO9VHsZrwyN2/8/cohX0wBqlaxLfy+v9+vkklHzzqjpjoTOHGDhm0tgFF15BAnx/vuenQYuRBM6gaeEraZGQN5yzeXm3pOa6i40tG0TihgIbFiV2Ynm2SfpP7UCC+okzvn9qqcE8ZcjIS/aZSIW+XFuFPw+DZF3Fz9E8vm2GV8iTfXxl788BGSsUPq0yS7UD3GMiCFikoy7V8UHSe0itXPEl5CxRIGd9/QTT0vcTELY3+lqN1W0Yz85wmdgrSw/YG1WxADRF0NL6ez/h+MldMQcdYz6oBfGqdK4WiuMTeF3utTQ9XzCHbmMHSLbrRB9wVKiCpER8f9w/AHQAcNkLX+L09dO7tNf5A4ZhTkA+wyQdHcTMdUbCa4N70sT2SPV0SsZuzY3Xi3zD6Bfj/R8kj82U9mSW3++V8rWUjAY150Vwa8qxABYpjEwJskm1HEfg/6Oi01HxGPL08n7vIlbJ4/9P2YzTom1DUQOheTlriFZ9K6EPCa6g91QSEqxDXS5drImWmFF1zbdrAHMhD2lvLvxua+0=}
bot:
  automerge: true
